### ISSUE TITLE
Javascript Error - Material-select with Angular in Dependent Dropdown

### ISSUE THREAD

**Issue by abhinandankothari** [krescruz/angular-materialize#33] opened 2015-06-14 08:57 UTC
I am getting the following error:

```
Uncaught TypeError: Cannot read property 'top' of undefined

$.fn.scrollTo @ dropdown.js?body=1:6

$.fn.material_select.$.each.activateOption @ forms.js?body=1:325

(anonymous function) @ forms.js?body=1:314

jQuery.event.dispatch @ jquery.js?body=1:4436

jQuery.event.add.elemData.handle @ jquery.js?body=1:4122
```

States is javascript object

```
window.States =
   "New York":
     ["Buffalo","Rochester"]
   "California":
     ["San Jose", "Los Angeles"]
```

Slim syntax of my applications code

```
 .input-field.col.s12.l6
   select#state material-select="" ng-model="centre.state" valueattr="value" ng-options="state for (state,city) in states"
      option value="" disabled="" selected="" Select State
 .input-field.col.s12.l6
    select#cities material-select=""  ng-model="centre.city" valueattr="value" ng-options="city for city in states[centre.state]"
       option value="" disabled="" selected="" Select City
```

This feature is a dependent dropdown which is not working with material-select i.e. Once State is selected then cities are to populated, It is working perfectly fine with Browser-default but not with Material select
Because of this i am unable to use material-select and have to fallback to browser-default which is giving a bad UI look throughout my application

**Comment by webbiesdk** [comment] 2015-06-14 10:21
A jsfiddle or a link would be nice.

**Comment by webbiesdk** [comment] 2015-07-27 16:03
This is a duplicate of #29 and properly related to #47. 

The TypeError that you had is caused by Materialize trying to focus an &lt;li&gt; tag that no longer exists. 

I'm looking a bit at it now, but continue discussion of this issue on #29.

**Closed as completed by webbiesdk** 2015-07-27 16:03 UTC

**Comment by abhinandankothari** [comment] 2015-07-30 13:18
@webbiesdk Thanks :+1:
