### ISSUE TITLE
Modal cannot be used if switching to MaterialCss 0.97.8

### ISSUE THREAD

**Issue by gaplo917** [krescruz/angular-materialize#207] opened 2016-11-23 16:07 UTC
0.97.7 tested, and it is ok. 

According to MaterialCss 0.97.8 Change Log

v0.97.8 (October 30th)
**Refactored Modal plugin**
Tabs now supported in navbar
Chips data can now be reinitiailized
Minor side nav fixes
FAB to toolbar component added
Fixed dropdown options bug

---

Error as shown 0.2.1 version angular-material
```
angular.js:13920 TypeError: element.leanModal is not a function
    at angular-materialize.js:1141
    at angular.js:19612
    at completeOutstandingRequest (angular.js:5964)
    at angular.js:6243
```

**Comment by strongant** [comment] 2016-11-24 02:16
I also encountered this error, select the drop to 0.97.7

**Comment by tobias-theobald** [comment] 2016-11-24 20:11
Duplicate of #202.

**Comment by heoheoyh** [comment] 2016-11-30 17:05
i got same error

**Comment by webbiesdk** [comment] 2016-12-23 21:58
Closed, duplicate of #202.

**Closed as completed by webbiesdk** 2016-12-23 21:58 UTC
