### ISSUE TITLE
format is not working in input-date

### ISSUE THREAD

**Issue by dhaval85** [krescruz/angular-materialize#129] opened 2016-02-29 08:20 UTC
I am trying this yyyy-mm-dd'T'HH:MM as format in input-date. However it's not working. It only replaces yyyy-mm-dd and nothing else. How to use full format there like I have?

Thanks,
Dhaval

**Comment by webbiesdk** [comment] 2016-05-15 10:53
Duplicate of #52?

**Closed as completed** 2016-05-20 13:56 UTC
Labels: duplicate
